consul:
    hostname: consul
    image: qnib/consul
    environment:
    - DC_NAME=dc1
    - RUN_SERVER=true
    - BOOTSTRAP_CONSUL=true
    ports:
    - "8500:8500"
    dns: 127.0.0.1

zookeeper0:
    hostname: zookeeper0
    dns: 127.0.0.1
    image: qnib/zookeeper
    # build: .
    environment:
    - DC_NAME=dc1
    - MYID=1
    links:
    - consul:consul
    ports:
    - 2181:2181
    privileged: true

zkui:
    hostname: zkui
    dns: 127.0.0.1
    dns_search:
    - node.consul
    - service.consul
    image: qnib/zkui
    environment:
    - DC_NAME=dc1
    links:
    - zookeeper0:zookeeper
    - consul:consul
    ports:
    - 9090:9090
    privileged: true

opentsdb:
    hostname: opentsdb
    dns: 127.0.0.1
    image: qnib/opentsdb
    #build: .
    environment:
    - DC_NAME=dc1
    links:
    - consul:consul
    ports:
    - 4242:4242
    - 8042:8042
    - 8088:8088
    - 50070:50070
    - 60000:60000
    - 60010:60010
    - 60030:60030

grafana2:
    image: qnib/grafana2
    dns: 127.0.0.1
    hostname: grafana2
    environment:
    - DC_NAME=dc1
    - RANDOM_METRICS=true
    ports:
    - 3000:3000
    links:
    - opentsdb
    - consul:consul
