consul:
    hostname: consul
    image: qnib/consul
    environment:
    - DC_NAME=dc1
    ports:
    - "8500:8500"
    dns: 127.0.0.1

opentsdb:
    hostname: opentsdb
    image: qnib/opentsdb
    #build: .
    environment:
    - DC_NAME=dc1
    links:
    - consul:consul
    ports:
    - 4242:4242
    - 60000:60000
    - 60010:60010
    - 60030:60030
